[package]
name = "translator-ocr"
version.workspace = true
edition = "2024"

[dependencies]
image = { workspace = true }
oar-ocr = { version = "0.9", features = ["directml"] }
reqwest = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
translator-core = { path = "../translator-core" }
