[package]
name = "translator-capture"
version.workspace = true
edition = "2024"

[dependencies]
arc-swap = { workspace = true }
bytes = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
windows = { workspace = true, features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging", "Win32_Graphics_Gdi", "Win32_Graphics_Dwm"] }
windows-capture = "2.0.0"
