name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read
  actions: write

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: cargo fmt
        run: cargo fmt --all -- --check

  build:
    uses: ./.github/workflows/build.yml
    with:
      check: true
      package: ${{ github.event_name == 'push' }}
