[package]
name = "translator-app"
version.workspace = true
edition = "2024"

[dependencies]
bytes = { workspace = true }
parking_lot = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
translator-capture = { path = "../translator-capture" }
translator-core = { path = "../translator-core" }
translator-ocr = { path = "../translator-ocr" }
translator-overlay = { path = "../translator-overlay" }
translator-translate = { path = "../translator-translate" }
windows = { workspace = true, features = ["Win32_Foundation", "Win32_UI_HiDpi", "Win32_UI_Shell", "Win32_UI_WindowsAndMessaging"] }
windows-canvas = { version = "0.100", features = ["reactor"] }
windows-collections = "0.100"
windows-core = "0.100"
windows-reactor = "0.100"
windows-reference = "0.100"
