[package]
name = "translator-app"
version.workspace = true
edition = "2024"

[dependencies]
anyhow = { workspace = true }
parking_lot = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
translator-capture = { path = "../translator-capture" }
translator-core = { path = "../translator-core" }
translator-ocr = { path = "../translator-ocr" }
translator-overlay = { path = "../translator-overlay" }
translator-translate = { path = "../translator-translate" }
windows = { workspace = true, features = ["Win32_UI_HiDpi"] }
windows-reactor = { git = "https://github.com/microsoft/windows-rs", version = "0.100.0" }

[build-dependencies]
windows-reactor-setup = { git = "https://github.com/microsoft/windows-rs", version = "0.100.0" }
